# -*- coding: utf-8 -*-
#
# Form implementation generated from reading ui file 'trialwindow2.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import ui_stylesheet

class Ui_trialwindow2(object):
    def setupUi(self, trialwindow2):
        trialwindow2.setObjectName("trialwindow2")
        trialwindow2.resize(920, 500)
        trialwindow2.setStyleSheet(ui_stylesheet.css)
        self.labelTitle = QtWidgets.QLabel(trialwindow2)
        self.labelTitle.setGeometry(QtCore.QRect(360, 10, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(14)
        self.labelTitle.setFont(font)
        self.labelTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.faculty_combobox = QtWidgets.QComboBox(trialwindow2)
        self.faculty_combobox.setGeometry(QtCore.QRect(20, 110, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.faculty_combobox.setFont(font)
        self.faculty_combobox.setObjectName("faculty_combobox")
        self.semester_combobox2 = QtWidgets.QComboBox(trialwindow2)
        self.semester_combobox2.setGeometry(QtCore.QRect(340, 110, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.semester_combobox2.setFont(font)
        self.semester_combobox2.setObjectName("semester_combobox2")
        self.section_combobox2 = QtWidgets.QComboBox(trialwindow2)
        self.section_combobox2.setGeometry(QtCore.QRect(480, 110, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.section_combobox2.setFont(font)
        self.section_combobox2.setObjectName("section_combobox2")
        self.subject_combobox2 = QtWidgets.QComboBox(trialwindow2)
        self.subject_combobox2.setGeometry(QtCore.QRect(620, 110, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.subject_combobox2.setFont(font)
        self.subject_combobox2.setObjectName("subject_combobox2")
        self.label = QtWidgets.QLabel(trialwindow2)
        self.label.setGeometry(QtCore.QRect(20, 80, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(trialwindow2)
        self.label_2.setGeometry(QtCore.QRect(340, 80, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(trialwindow2)
        self.label_3.setGeometry(QtCore.QRect(480, 80, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(trialwindow2)
        self.label_4.setGeometry(QtCore.QRect(620, 80, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.assignBtn = QtWidgets.QPushButton(trialwindow2)
        self.assignBtn.setGeometry(QtCore.QRect(20, 440, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(11)
        self.assignBtn.setFont(font)
        self.assignBtn.setObjectName("assignBtn")
        self.backBtn = QtWidgets.QPushButton(trialwindow2)
        self.backBtn.setGeometry(QtCore.QRect(630, 440, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(11)
        self.backBtn.setFont(font)
        self.backBtn.setObjectName("backBtn")
        self.nextBtn = QtWidgets.QPushButton(trialwindow2)
        self.nextBtn.setGeometry(QtCore.QRect(770, 440, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(11)
        self.nextBtn.setFont(font)
        self.nextBtn.setObjectName("nextBtn")
        self.assigned_list = QtWidgets.QListWidget(trialwindow2)
        self.assigned_list.setGeometry(QtCore.QRect(20, 160, 881, 261))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.assigned_list.setFont(font)
        self.assigned_list.setAlternatingRowColors(True)
        self.assigned_list.setObjectName("assigned_list")
        self.undoBtn = QtWidgets.QPushButton(trialwindow2)
        self.undoBtn.setGeometry(QtCore.QRect(180, 440, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(11)
        self.undoBtn.setFont(font)
        self.undoBtn.setObjectName("undoBtn")

        self.retranslateUi(trialwindow2)
        QtCore.QMetaObject.connectSlotsByName(trialwindow2)

    def retranslateUi(self, trialwindow2):
        _translate = QtCore.QCoreApplication.translate
        trialwindow2.setWindowTitle(_translate("trialwindow2", "Form"))
        self.labelTitle.setText(_translate("trialwindow2", "Faculty Assignment"))
        self.label.setText(_translate("trialwindow2", "Faculty :"))
        self.label_2.setText(_translate("trialwindow2", "Semester :"))
        self.label_3.setText(_translate("trialwindow2", "Section :"))
        self.label_4.setText(_translate("trialwindow2", "Subject :"))
        self.assignBtn.setText(_translate("trialwindow2", "Assign"))
        self.backBtn.setText(_translate("trialwindow2", "< Back"))
        self.nextBtn.setText(_translate("trialwindow2", "Next >"))
        self.undoBtn.setText(_translate("trialwindow2", "Undo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    trialwindow2 = QtWidgets.QWidget()
    ui = Ui_trialwindow2()
    ui.setupUi(trialwindow2)
    trialwindow2.show()
    sys.exit(app.exec_())

