# -*- coding: utf-8 -*-
#
# Form implementation generated from reading ui file 'trialwindow4.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import ui_stylesheet

class Ui_trialwindow4(object):
    def setupUi(self, trialwindow4):
        trialwindow4.setObjectName("trialwindow4")
        trialwindow4.resize(920, 500)
        trialwindow4.setStyleSheet(ui_stylesheet.css)
        self.labelTitle = QtWidgets.QLabel(trialwindow4)
        self.labelTitle.setGeometry(QtCore.QRect(390, 10, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(14)
        self.labelTitle.setFont(font)
        self.labelTitle.setObjectName("labelTitle")
        self.label_faculty = QtWidgets.QLabel(trialwindow4)
        self.label_faculty.setGeometry(QtCore.QRect(50, 80, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(11)
        self.label_faculty.setFont(font)
        self.label_faculty.setObjectName("label_faculty")
        self.faculty_combobox = QtWidgets.QComboBox(trialwindow4)
        self.faculty_combobox.setGeometry(QtCore.QRect(110, 80, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.faculty_combobox.setFont(font)
        self.faculty_combobox.setObjectName("faculty_combobox")
        self.faculty_table = QtWidgets.QTableWidget(trialwindow4)
        self.faculty_table.setGeometry(QtCore.QRect(10, 130, 901, 291))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.faculty_table.setFont(font)
        self.faculty_table.setStyleSheet("td {\n"
"    padding:10px;\n"
"}")
        self.faculty_table.setObjectName("faculty_table")
        self.faculty_table.setColumnCount(8)
        self.faculty_table.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        item.setFont(font)
        self.faculty_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.faculty_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.faculty_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.faculty_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.faculty_table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.faculty_table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.faculty_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.faculty_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.faculty_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.faculty_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.faculty_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.faculty_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.faculty_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.faculty_table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        item.setFont(font)
        self.faculty_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        item.setFont(font)
        self.faculty_table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        item.setFont(font)
        self.faculty_table.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        item.setFont(font)
        self.faculty_table.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        item.setFont(font)
        self.faculty_table.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        item.setFont(font)
        self.faculty_table.setItem(5, 0, item)
        self.faculty_table.horizontalHeader().setDefaultSectionSize(100)
        self.faculty_table.horizontalHeader().setMinimumSectionSize(37)
        self.faculty_table.verticalHeader().setDefaultSectionSize(43)
        self.faculty_table.verticalHeader().setMinimumSectionSize(27)
        self.backBtn = QtWidgets.QPushButton(trialwindow4)
        self.backBtn.setGeometry(QtCore.QRect(630, 440, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(11)
        self.backBtn.setFont(font)
        self.backBtn.setObjectName("backBtn")
        self.saveBtn = QtWidgets.QPushButton(trialwindow4)
        self.saveBtn.setGeometry(QtCore.QRect(20, 440, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(11)
        self.saveBtn.setFont(font)
        self.saveBtn.setObjectName("saveBtn")
        self.printBtn = QtWidgets.QPushButton(trialwindow4)
        self.printBtn.setGeometry(QtCore.QRect(180, 440, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(11)
        self.printBtn.setFont(font)
        self.printBtn.setObjectName("printBtn")
        self.generateBtn = QtWidgets.QPushButton(trialwindow4)
        self.generateBtn.setGeometry(QtCore.QRect(770, 440, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(11)
        self.generateBtn.setFont(font)
        self.generateBtn.setObjectName("generateBtn")

        self.retranslateUi(trialwindow4)
        QtCore.QMetaObject.connectSlotsByName(trialwindow4)

    def retranslateUi(self, trialwindow4):
        _translate = QtCore.QCoreApplication.translate
        trialwindow4.setWindowTitle(_translate("trialwindow4", "Form"))
        self.labelTitle.setText(_translate("trialwindow4", "Faculty Contraints"))
        self.label_faculty.setText(_translate("trialwindow4", "Faculty :"))
        item = self.faculty_table.verticalHeaderItem(0)
        item.setText(_translate("trialwindow4", "Monday"))
        item = self.faculty_table.verticalHeaderItem(1)
        item.setText(_translate("trialwindow4", "Tuesday"))
        item = self.faculty_table.verticalHeaderItem(2)
        item.setText(_translate("trialwindow4", "Wednesday"))
        item = self.faculty_table.verticalHeaderItem(3)
        item.setText(_translate("trialwindow4", "Thursday"))
        item = self.faculty_table.verticalHeaderItem(4)
        item.setText(_translate("trialwindow4", "Friday"))
        item = self.faculty_table.verticalHeaderItem(5)
        item.setText(_translate("trialwindow4", "Saturday"))
        item = self.faculty_table.horizontalHeaderItem(0)
        item.setText(_translate("trialwindow4", "9:00-9:55"))
        item = self.faculty_table.horizontalHeaderItem(1)
        item.setText(_translate("trialwindow4", "9:55-10:50"))
        item = self.faculty_table.horizontalHeaderItem(2)
        item.setText(_translate("trialwindow4", "11:10-12:05"))
        item = self.faculty_table.horizontalHeaderItem(3)
        item.setText(_translate("trialwindow4", "12:05-1:00"))
        item = self.faculty_table.horizontalHeaderItem(4)
        item.setText(_translate("trialwindow4", "1:00-1:55"))
        item = self.faculty_table.horizontalHeaderItem(5)
        item.setText(_translate("trialwindow4", "1:55-2:50"))
        item = self.faculty_table.horizontalHeaderItem(6)
        item.setText(_translate("trialwindow4", "2:50-3:40"))
        item = self.faculty_table.horizontalHeaderItem(7)
        item.setText(_translate("trialwindow4", "3:40-4:30"))
        __sortingEnabled = self.faculty_table.isSortingEnabled()
        self.faculty_table.setSortingEnabled(False)
        self.faculty_table.setSortingEnabled(__sortingEnabled)
        self.backBtn.setText(_translate("trialwindow4", "< Back"))
        self.saveBtn.setText(_translate("trialwindow4", "Save"))
        self.printBtn.setText(_translate("trialwindow4", "Print"))
        self.generateBtn.setText(_translate("trialwindow4", "Generate >"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    trialwindow4 = QtWidgets.QWidget()
    ui = Ui_trialwindow4()
    ui.setupUi(trialwindow4)
    trialwindow4.show()
    sys.exit(app.exec_())

