# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trialwindow3.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import ui_stylesheet

class Ui_trialwindow3(object):
    def setupUi(self, trialwindow3):
        trialwindow3.setObjectName("trialwindow3")
        trialwindow3.resize(920, 500)
        trialwindow3.setStyleSheet(ui_stylesheet.css)
        self.label = QtWidgets.QLabel(trialwindow3)
        self.label.setGeometry(QtCore.QRect(390, 10, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(trialwindow3)
        self.label_2.setGeometry(QtCore.QRect(40, 90, 64, 16))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(trialwindow3)
        self.label_3.setGeometry(QtCore.QRect(250, 90, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(trialwindow3)
        self.label_4.setGeometry(QtCore.QRect(590, 90, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.semester_combobox = QtWidgets.QComboBox(trialwindow3)
        self.semester_combobox.setGeometry(QtCore.QRect(110, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.semester_combobox.setFont(font)
        self.semester_combobox.setObjectName("semester_combobox")
        self.section_combobox = QtWidgets.QComboBox(trialwindow3)
        self.section_combobox.setGeometry(QtCore.QRect(310, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.section_combobox.setFont(font)
        self.section_combobox.setObjectName("section_combobox")
        self.slotType_combobox = QtWidgets.QComboBox(trialwindow3)
        self.slotType_combobox.setGeometry(QtCore.QRect(670, 80, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.slotType_combobox.setFont(font)
        self.slotType_combobox.setObjectName("slotType_combobox")
        self.saveBtn = QtWidgets.QPushButton(trialwindow3)
        self.saveBtn.setGeometry(QtCore.QRect(20, 440, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(11)
        self.saveBtn.setFont(font)
        self.saveBtn.setObjectName("saveBtn")
        self.printBtn = QtWidgets.QPushButton(trialwindow3)
        self.printBtn.setGeometry(QtCore.QRect(180, 440, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(11)
        self.printBtn.setFont(font)
        self.printBtn.setObjectName("printBtn")
        self.backBtn = QtWidgets.QPushButton(trialwindow3)
        self.backBtn.setGeometry(QtCore.QRect(630, 440, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(11)
        self.backBtn.setFont(font)
        self.backBtn.setObjectName("backBtn")
        self.nextBtn = QtWidgets.QPushButton(trialwindow3)
        self.nextBtn.setGeometry(QtCore.QRect(770, 440, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(11)
        self.nextBtn.setFont(font)
        self.nextBtn.setObjectName("nextBtn")
        self.subject_table = QtWidgets.QTableWidget(trialwindow3)
        self.subject_table.setGeometry(QtCore.QRect(10, 130, 901, 291))
        self.subject_table.setStyleSheet("td {\n"
"    padding:10px;\n"
"}")
        self.subject_table.setObjectName("subject_table")
        self.subject_table.setColumnCount(8)
        self.subject_table.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        item.setFont(font)
        self.subject_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.subject_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.subject_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.subject_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.subject_table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.subject_table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.subject_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.subject_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.subject_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.subject_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.subject_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.subject_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.subject_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.subject_table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        item.setFont(font)
        self.subject_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        item.setFont(font)
        self.subject_table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        item.setFont(font)
        self.subject_table.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        item.setFont(font)
        self.subject_table.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        item.setFont(font)
        self.subject_table.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        item.setFont(font)
        self.subject_table.setItem(5, 0, item)
        self.subject_table.horizontalHeader().setDefaultSectionSize(100)
        self.subject_table.horizontalHeader().setMinimumSectionSize(37)
        self.subject_table.verticalHeader().setDefaultSectionSize(43)
        self.subject_table.verticalHeader().setMinimumSectionSize(27)

        self.retranslateUi(trialwindow3)
        QtCore.QMetaObject.connectSlotsByName(trialwindow3)

    def retranslateUi(self, trialwindow3):
        _translate = QtCore.QCoreApplication.translate
        trialwindow3.setWindowTitle(_translate("trialwindow3", "Form"))
        self.label.setText(_translate("trialwindow3", "Subject Constraints"))
        self.label_2.setText(_translate("trialwindow3", "Semester :"))
        self.label_3.setText(_translate("trialwindow3", "Section :"))
        self.label_4.setText(_translate("trialwindow3", "Slot Type :"))
        self.saveBtn.setText(_translate("trialwindow3", "Save"))
        self.printBtn.setText(_translate("trialwindow3", "Print"))
        self.backBtn.setText(_translate("trialwindow3", "< Back"))
        self.nextBtn.setText(_translate("trialwindow3", "Next >"))
        item = self.subject_table.verticalHeaderItem(0)
        item.setText(_translate("trialwindow3", "Monday"))
        item = self.subject_table.verticalHeaderItem(1)
        item.setText(_translate("trialwindow3", "Tuesday"))
        item = self.subject_table.verticalHeaderItem(2)
        item.setText(_translate("trialwindow3", "Wednesday"))
        item = self.subject_table.verticalHeaderItem(3)
        item.setText(_translate("trialwindow3", "Thursday"))
        item = self.subject_table.verticalHeaderItem(4)
        item.setText(_translate("trialwindow3", "Friday"))
        item = self.subject_table.verticalHeaderItem(5)
        item.setText(_translate("trialwindow3", "Saturday"))
        item = self.subject_table.horizontalHeaderItem(0)
        item.setText(_translate("trialwindow3", "9:00-9:55"))
        item = self.subject_table.horizontalHeaderItem(1)
        item.setText(_translate("trialwindow3", "9:55-10:50"))
        item = self.subject_table.horizontalHeaderItem(2)
        item.setText(_translate("trialwindow3", "11:10-12:05"))
        item = self.subject_table.horizontalHeaderItem(3)
        item.setText(_translate("trialwindow3", "12:05-1:00"))
        item = self.subject_table.horizontalHeaderItem(4)
        item.setText(_translate("trialwindow3", "1:00-1:55"))
        item = self.subject_table.horizontalHeaderItem(5)
        item.setText(_translate("trialwindow3", "1:55-2:50"))
        item = self.subject_table.horizontalHeaderItem(6)
        item.setText(_translate("trialwindow3", "2:50-3:40"))
        item = self.subject_table.horizontalHeaderItem(7)
        item.setText(_translate("trialwindow3", "3:40-4:30"))
        __sortingEnabled = self.subject_table.isSortingEnabled()
        self.subject_table.setSortingEnabled(False)
        self.subject_table.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    trialwindow3 = QtWidgets.QWidget()
    ui = Ui_trialwindow3()
    ui.setupUi(trialwindow3)
    trialwindow3.show()
    sys.exit(app.exec_())

