# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'year_window.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import lightstyle

class Ui_year_window(object):
    def setupUi(self, year_window):
        year_window.setObjectName("year_window")
        year_window.resize(630, 212)
        year_window.setStyleSheet(lightstyle.css)
        year_window.setWindowIcon(QtGui.QIcon('icons/favicon.ico'))
        self.gridLayoutWidget = QtWidgets.QWidget(year_window)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 631, 211))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(7, 0, 7, 6)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 4, 1, 1)
        self.endYear_dateedit = QtWidgets.QDateEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endYear_dateedit.sizePolicy().hasHeightForWidth())
        self.endYear_dateedit.setSizePolicy(sizePolicy)
        self.endYear_dateedit.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.endYear_dateedit.setFont(font)
        self.endYear_dateedit.setObjectName("endYear_dateedit")
        self.gridLayout_2.addWidget(self.endYear_dateedit, 3, 4, 1, 1)
        self.endMonth_combobox = QtWidgets.QComboBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endMonth_combobox.sizePolicy().hasHeightForWidth())
        self.endMonth_combobox.setSizePolicy(sizePolicy)
        self.endMonth_combobox.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.endMonth_combobox.setFont(font)
        self.endMonth_combobox.setObjectName("endMonth_combobox")
        self.gridLayout_2.addWidget(self.endMonth_combobox, 3, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 4, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 3, 1, 1)
        self.startMonth_combobox = QtWidgets.QComboBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startMonth_combobox.sizePolicy().hasHeightForWidth())
        self.startMonth_combobox.setSizePolicy(sizePolicy)
        self.startMonth_combobox.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.startMonth_combobox.setFont(font)
        self.startMonth_combobox.setObjectName("startMonth_combobox")
        self.gridLayout_2.addWidget(self.startMonth_combobox, 3, 0, 1, 1)
        self.startYear_dateedit = QtWidgets.QDateEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startYear_dateedit.sizePolicy().hasHeightForWidth())
        self.startYear_dateedit.setSizePolicy(sizePolicy)
        self.startYear_dateedit.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.startYear_dateedit.setFont(font)
        self.startYear_dateedit.setObjectName("startYear_dateedit")
        self.gridLayout_2.addWidget(self.startYear_dateedit, 3, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 0, 2, 5, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 3, 1, 2)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.skipBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skipBtn.sizePolicy().hasHeightForWidth())
        self.skipBtn.setSizePolicy(sizePolicy)
        self.skipBtn.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.skipBtn.setFont(font)
        self.skipBtn.setObjectName("skipBtn")
        self.horizontalLayout_2.addWidget(self.skipBtn)
        self.continueBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.continueBtn.sizePolicy().hasHeightForWidth())
        self.continueBtn.setSizePolicy(sizePolicy)
        self.continueBtn.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.continueBtn.setFont(font)
        self.continueBtn.setObjectName("continueBtn")
        self.horizontalLayout_2.addWidget(self.continueBtn)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)

        self.retranslateUi(year_window)
        QtCore.QMetaObject.connectSlotsByName(year_window)
        year_window.setTabOrder(self.startMonth_combobox, self.startYear_dateedit)
        year_window.setTabOrder(self.startYear_dateedit, self.endMonth_combobox)
        year_window.setTabOrder(self.endMonth_combobox, self.endYear_dateedit)
        year_window.setTabOrder(self.endYear_dateedit, self.skipBtn)
        year_window.setTabOrder(self.skipBtn, self.continueBtn)

    def retranslateUi(self, year_window):
        _translate = QtCore.QCoreApplication.translate
        year_window.setWindowTitle(_translate("year_window", "Set Academic Year"))
        self.label.setText(_translate("year_window", "Set Academic Year"))
        self.label_6.setText(_translate("year_window", "Year:"))
        self.endYear_dateedit.setDisplayFormat(_translate("year_window", "yyyy"))
        self.label_4.setText(_translate("year_window", "Month:"))
        self.label_7.setText(_translate("year_window", "Year:"))
        self.label_5.setText(_translate("year_window", "Month:"))
        self.startYear_dateedit.setDisplayFormat(_translate("year_window", "yyyy"))
        self.label_2.setText(_translate("year_window", "Start Date:"))
        self.label_3.setText(_translate("year_window", "End Date:"))
        self.skipBtn.setText(_translate("year_window", "Skip"))
        self.continueBtn.setText(_translate("year_window", "Continue"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    year_window = QtWidgets.QDialog()
    ui = Ui_year_window()
    ui.setupUi(year_window)
    year_window.show()
    sys.exit(app.exec_())

