# -*- coding: utf-8 -*-
#
# Form implementation generated from reading ui file 'trialwindow5.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import ui_stylesheet

class Ui_trialwindow5(object):
    def setupUi(self, trialwindow5):
        trialwindow5.setObjectName("trialwindow5")
        trialwindow5.resize(920, 500)
        trialwindow5.setStyleSheet(ui_stylesheet.css)
        self.labelTitle = QtWidgets.QLabel(trialwindow5)
        self.labelTitle.setGeometry(QtCore.QRect(370, 10, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(14)
        self.labelTitle.setFont(font)
        self.labelTitle.setObjectName("labelTitle")
        self.printBtn = QtWidgets.QPushButton(trialwindow5)
        self.printBtn.setGeometry(QtCore.QRect(180, 440, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(11)
        self.printBtn.setFont(font)
        self.printBtn.setObjectName("printBtn")
        self.faculty_table = QtWidgets.QTableWidget(trialwindow5)
        self.faculty_table.setGeometry(QtCore.QRect(10, 130, 901, 291))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.faculty_table.setFont(font)
        self.faculty_table.setObjectName("faculty_table")
        self.faculty_table.setColumnCount(8)
        self.faculty_table.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        item.setFont(font)
        self.faculty_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.faculty_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.faculty_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.faculty_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.faculty_table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.faculty_table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.faculty_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.faculty_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.faculty_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.faculty_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.faculty_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.faculty_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.faculty_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.faculty_table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        item.setFont(font)
        self.faculty_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        item.setFont(font)
        self.faculty_table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        item.setFont(font)
        self.faculty_table.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        item.setFont(font)
        self.faculty_table.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        item.setFont(font)
        self.faculty_table.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        item.setFont(font)
        self.faculty_table.setItem(5, 0, item)
        self.faculty_table.horizontalHeader().setDefaultSectionSize(100)
        self.faculty_table.horizontalHeader().setMinimumSectionSize(37)
        self.faculty_table.verticalHeader().setDefaultSectionSize(43)
        self.faculty_table.verticalHeader().setMinimumSectionSize(27)
        self.backBtn = QtWidgets.QPushButton(trialwindow5)
        self.backBtn.setGeometry(QtCore.QRect(630, 440, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(11)
        self.backBtn.setFont(font)
        self.backBtn.setObjectName("backBtn")
        self.saveBtn = QtWidgets.QPushButton(trialwindow5)
        self.saveBtn.setGeometry(QtCore.QRect(20, 440, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(11)
        self.saveBtn.setFont(font)
        self.saveBtn.setObjectName("saveBtn")
        self.label_2 = QtWidgets.QLabel(trialwindow5)
        self.label_2.setGeometry(QtCore.QRect(260, 90, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.section_combobox = QtWidgets.QComboBox(trialwindow5)
        self.section_combobox.setGeometry(QtCore.QRect(480, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.section_combobox.setFont(font)
        self.section_combobox.setObjectName("section_combobox")
        self.semester_combobox = QtWidgets.QComboBox(trialwindow5)
        self.semester_combobox.setGeometry(QtCore.QRect(330, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.semester_combobox.setFont(font)
        self.semester_combobox.setObjectName("semester_combobox")
        self.label_3 = QtWidgets.QLabel(trialwindow5)
        self.label_3.setGeometry(QtCore.QRect(420, 90, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.finishBtn = QtWidgets.QPushButton(trialwindow5)
        self.finishBtn.setGeometry(QtCore.QRect(770, 440, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(11)
        self.finishBtn.setFont(font)
        self.finishBtn.setObjectName("finishBtn")
        self.faculty_combobox = QtWidgets.QComboBox(trialwindow5)
        self.faculty_combobox.setGeometry(QtCore.QRect(640, 80, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.faculty_combobox.setFont(font)
        self.faculty_combobox.setObjectName("faculty_combobox")
        self.label_faculty = QtWidgets.QLabel(trialwindow5)
        self.label_faculty.setGeometry(QtCore.QRect(580, 80, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(10)
        self.label_faculty.setFont(font)
        self.label_faculty.setObjectName("label_faculty")
        self.label = QtWidgets.QLabel(trialwindow5)
        self.label.setGeometry(QtCore.QRect(20, 80, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.inputType_combobox = QtWidgets.QComboBox(trialwindow5)
        self.inputType_combobox.setGeometry(QtCore.QRect(100, 80, 141, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.inputType_combobox.setFont(font)
        self.inputType_combobox.setObjectName("inputType_combobox")

        self.retranslateUi(trialwindow5)
        QtCore.QMetaObject.connectSlotsByName(trialwindow5)

    def retranslateUi(self, trialwindow5):
        _translate = QtCore.QCoreApplication.translate
        trialwindow5.setWindowTitle(_translate("trialwindow5", "Form"))
        self.labelTitle.setText(_translate("trialwindow5", "Generated Timetable"))
        self.printBtn.setText(_translate("trialwindow5", "Print"))
        item = self.faculty_table.verticalHeaderItem(0)
        item.setText(_translate("trialwindow5", "Monday"))
        item = self.faculty_table.verticalHeaderItem(1)
        item.setText(_translate("trialwindow5", "Tuesday"))
        item = self.faculty_table.verticalHeaderItem(2)
        item.setText(_translate("trialwindow5", "Wednesday"))
        item = self.faculty_table.verticalHeaderItem(3)
        item.setText(_translate("trialwindow5", "Thursday"))
        item = self.faculty_table.verticalHeaderItem(4)
        item.setText(_translate("trialwindow5", "Friday"))
        item = self.faculty_table.verticalHeaderItem(5)
        item.setText(_translate("trialwindow5", "Saturday"))
        item = self.faculty_table.horizontalHeaderItem(0)
        item.setText(_translate("trialwindow5", "9:00-9:55"))
        item = self.faculty_table.horizontalHeaderItem(1)
        item.setText(_translate("trialwindow5", "9:55-10:50"))
        item = self.faculty_table.horizontalHeaderItem(2)
        item.setText(_translate("trialwindow5", "11:10-12:05"))
        item = self.faculty_table.horizontalHeaderItem(3)
        item.setText(_translate("trialwindow5", "12:05-1:00"))
        item = self.faculty_table.horizontalHeaderItem(4)
        item.setText(_translate("trialwindow5", "1:00-1:55"))
        item = self.faculty_table.horizontalHeaderItem(5)
        item.setText(_translate("trialwindow5", "1:55-2:50"))
        item = self.faculty_table.horizontalHeaderItem(6)
        item.setText(_translate("trialwindow5", "2:50-3:40"))
        item = self.faculty_table.horizontalHeaderItem(7)
        item.setText(_translate("trialwindow5", "3:40-4:30"))
        __sortingEnabled = self.faculty_table.isSortingEnabled()
        self.faculty_table.setSortingEnabled(False)
        self.faculty_table.setSortingEnabled(__sortingEnabled)
        self.backBtn.setText(_translate("trialwindow5", "< Back"))
        self.saveBtn.setText(_translate("trialwindow5", "Save"))
        self.label_2.setText(_translate("trialwindow5", "Semester :"))
        self.label_3.setText(_translate("trialwindow5", "Section :"))
        self.finishBtn.setText(_translate("trialwindow5", "Finish"))
        self.label_faculty.setText(_translate("trialwindow5", "Faculty :"))
        self.label.setText(_translate("trialwindow5", "Input Type :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    trialwindow5 = QtWidgets.QWidget()
    ui = Ui_trialwindow5()
    ui.setupUi(trialwindow5)
    trialwindow5.show()
    sys.exit(app.exec_())

